const fs = require('fs');

const file = 'src/utils/localizationSystem.ts';
let content = fs.readFileSync(file, 'utf8');

const keysToAdd = {
  'en-GB': {
    'UC_COMMON': 'Common',
    'UC_TIER': 'Tier',
    'UC_INIT_HEADER': 'PLAYER CARD INITIALIZATION',
    'UC_STEP_1_3': 'STEP 1 OF 3',
    'UC_TITLE': 'Initialize Your Wonderkid',
    'UC_SUBTITLE': 'Customize player identity & attributes or select a legendary preset',
    'CRASH_SHARE_SUCCESS': 'Crash report link copied to clipboard!',
    'MM_NO_SAVE_DESC': 'No active career save found. Start a new career to begin.',
    'MM_ACHIEVEMENTS_DESC': 'View your trophy cabinet, milestones, and career records.',
    'BTN_SELECT': 'Select',
    'SHOW': 'SHOW',
    'CASH': 'Cash',
    'PARENTS_ADVICE': "PARENTS' ADVICE",
    'HIDE': 'HIDE',
    'PANEL_CHEMISTRY': 'CHEMISTRY',
    'PANEL_FITNESS': 'FITNESS',
    'HEAL': 'HEAL',
    'AVAIL_MONEY': 'Available Money',
    'FAME': 'FAME',
    'BAD_REP': 'BAD REPUTATION',
    'TRAINING_PROGRESS': 'TRAINING PROGRESS',
    'CAREER_CALENDAR': 'CAREER CALENDAR',
    'PLAYER_CARD_OVERVIEW': 'PLAYER CARD OVERVIEW',
    'CUSTOMIZATION': 'CUSTOMIZATION',
    'PANEL_CAREER_PANELS': 'CAREER PANELS',
    'TAB_STORE': 'Store & Equipment',
    'TAB_CARDS': 'Card Collection',
    'TAB_DEV': 'Development & Stats',
    'TAB_ACCOUNTING': 'Accounting & Finances',
    'TAB_MANAGER': 'Player Agent & Manager',
    'TAB_SETTINGS': 'Settings',
    'TAB_TROPHIES': 'Trophy Cabinet',
    'TAB_PERKS': 'Career Perks',
    'TAB_NATIONAL_TEAM': 'National Team',
    'NATIONAL_TEAM_HUB': 'National Team Hub',
    'PANEL_CARD_EVENT': 'CARD EVENT',
    'PANEL_CAREER_SUMMARY': 'CAREER SUMMARY',
    'PANEL_RETIREMENT': 'RETIREMENT',
    'ATTR_SAVING': 'Saving',
    'ATTR_REFLEXES': 'Reflexes',
    'ATTR_HANDLING': 'Handling',
    'ATTR_POSITIONING': 'Positioning',
    'ATTR_AERIAL_REACH': 'Aerial Reach',
    'ATTR_ONE_ON_ONE': 'One-on-One',
    'ATTR_DISTRIBUTION': 'Distribution',
    'ATTR_PRO': 'Progression',
    'ATTR_DEF': 'Defense',
    'ATTR_CRE': 'Creation',
    'ATTR_MEN': 'Mentality',
    'ATTR_GOA': 'Goalscoring',
    'ATTR_PHY': 'Physicality',
    'SETTINGS_TEST_MODE': 'TEST MODE',
    'SETTINGS_TEST_MODE_DESC': 'Show test and developer options in gameplay.',
    'OPTION_ON': 'ON',
    'OPTION_OFF': 'OFF',
    'SETTINGS_APP_PREFERENCES': 'App Preferences & Typography Size',
    'SETTINGS_FONT_SIZE': 'Font Size Scale',
    'FONT_SIZE_SM': 'Small',
    'FONT_SIZE_MD': 'Medium',
    'FONT_SIZE_LG': 'Large',
    'BTN_RETURN_TO_SIMULATION': 'Return to Simulation',
  },
  'es-ES': {
    'UC_COMMON': 'Común',
    'UC_TIER': 'Nivel',
    'UC_INIT_HEADER': 'INICIALIZACIÓN DE LA CARTA',
    'UC_STEP_1_3': 'PASO 1 DE 3',
    'UC_TITLE': 'Inicializa tu Promesa',
    'UC_SUBTITLE': 'Personaliza la identidad y atributos o elige una leyenda preestablecida',
    'CRASH_SHARE_SUCCESS': '¡Informe de errores copiado al portapapeles!',
    'MM_NO_SAVE_DESC': 'No se encontró partida guardada. Inicia una nueva carrera.',
    'MM_ACHIEVEMENTS_DESC': 'Consulta tu vitrina de trofeos, hitos y récords de carrera.',
    'BTN_SELECT': 'Seleccionar',
    'SHOW': 'MOSTRAR',
    'CASH': 'Fondos',
    'PARENTS_ADVICE': 'CONSEJO FAMILIAR',
    'HIDE': 'OCULTAR',
    'PANEL_CHEMISTRY': 'QUÍMICA',
    'PANEL_FITNESS': 'FORMA FÍSICA',
    'HEAL': 'CURAR',
    'AVAIL_MONEY': 'Dinero Disponible',
    'FAME': 'FAMA',
    'BAD_REP': 'MALA REPUTACIÓN',
    'TRAINING_PROGRESS': 'PROGRESO DE ENTRENAMIENTO',
    'CAREER_CALENDAR': 'CALENDARIO DE CARRERA',
    'PLAYER_CARD_OVERVIEW': 'VISTA DE LA CARTA',
    'CUSTOMIZATION': 'PERSONALIZACIÓN',
    'PANEL_CAREER_PANELS': 'PANELES DE CARRERA',
    'TAB_STORE': 'Tienda y Equipamiento',
    'TAB_CARDS': 'Colección de Cartas',
    'TAB_DEV': 'Desarrollo y Atributos',
    'TAB_ACCOUNTING': 'Finanzas y Contabilidad',
    'TAB_MANAGER': 'Representante y Mánager',
    'TAB_SETTINGS': 'Ajustes',
    'TAB_TROPHIES': 'Vitrina de Trofeos',
    'TAB_PERKS': 'Perks de Carrera',
    'TAB_NATIONAL_TEAM': 'Selección Nacional',
    'NATIONAL_TEAM_HUB': 'Centro de la Selección',
    'PANEL_CARD_EVENT': 'EVENTO DE CARTAS',
    'PANEL_CAREER_SUMMARY': 'RESUMEN DE CARRERA',
    'PANEL_RETIREMENT': 'RETIRADA',
    'ATTR_SAVING': 'Paradas',
    'ATTR_REFLEXES': 'Reflejos',
    'ATTR_HANDLING': 'Blocaje',
    'ATTR_POSITIONING': 'Colocación',
    'ATTR_AERIAL_REACH': 'Alcance Aéreo',
    'ATTR_ONE_ON_ONE': 'Mano a Mano',
    'ATTR_DISTRIBUTION': 'Saque / Pase',
    'ATTR_PRO': 'Progresión',
    'ATTR_DEF': 'Defensa',
    'ATTR_CRE': 'Creación',
    'ATTR_MEN': 'Mentalidad',
    'ATTR_GOA': 'Gol',
    'ATTR_PHY': 'Físico',
    'SETTINGS_TEST_MODE': 'MODO DE PRUEBA',
    'SETTINGS_TEST_MODE_DESC': 'Mostrar opciones de desarrollo y pruebas durante el juego.',
    'OPTION_ON': 'ACTIVADO',
    'OPTION_OFF': 'DESACTIVADO',
    'SETTINGS_APP_PREFERENCES': 'Preferencias de la App y Tamaño de Fuente',
    'SETTINGS_FONT_SIZE': 'Escala de Tamaño de Fuente',
    'FONT_SIZE_SM': 'Pequeño',
    'FONT_SIZE_MD': 'Mediano',
    'FONT_SIZE_LG': 'Grande',
    'BTN_RETURN_TO_SIMULATION': 'Volver a la Simulación',
  },
  'es-AR': {
    'UC_COMMON': 'Común',
    'UC_TIER': 'Nivel',
    'UC_INIT_HEADER': 'INICIALIZACIÓN DE LA CARTA',
    'UC_STEP_1_3': 'PASO 1 DE 3',
    'UC_TITLE': 'Inicializá tu Joya',
    'UC_SUBTITLE': 'Personalizá identidad y stats o elegí una leyenda preestablecida',
    'CRASH_SHARE_SUCCESS': '¡Informe de errores copiado al portapapeles!',
    'MM_NO_SAVE_DESC': 'No se encontró partida guardada. Empezá una nueva carrera.',
    'MM_ACHIEVEMENTS_DESC': 'Revisá tu vitrina de trofeos, logros y récords de carrera.',
    'BTN_SELECT': 'Seleccionar',
    'SHOW': 'MOSTRAR',
    'CASH': 'Plata',
    'PARENTS_ADVICE': 'CONSEJO FAMILIAR',
    'HIDE': 'OCULTAR',
    'PANEL_CHEMISTRY': 'QUÍMICA',
    'PANEL_FITNESS': 'FORMA FÍSICA',
    'HEAL': 'CURAR',
    'AVAIL_MONEY': 'Plata Disponible',
    'FAME': 'FAMA',
    'BAD_REP': 'MALA FAMA',
    'TRAINING_PROGRESS': 'PROGRESO DE ENTRENAMIENTO',
    'CAREER_CALENDAR': 'CALENDARIO DE CARRERA',
    'PLAYER_CARD_OVERVIEW': 'VISTA DE LA CARTA',
    'CUSTOMIZATION': 'PERSONALIZACIÓN',
    'PANEL_CAREER_PANELS': 'PANELES DE CARRERA',
    'TAB_STORE': 'Tienda y Equipamiento',
    'TAB_CARDS': 'Colección de Cartas',
    'TAB_DEV': 'Desarrollo y Atributos',
    'TAB_ACCOUNTING': 'Finanzas y Contabilidad',
    'TAB_MANAGER': 'Representante y DT',
    'TAB_SETTINGS': 'Ajustes',
    'TAB_TROPHIES': 'Vitrina de Trofeos',
    'TAB_PERKS': 'Perks de Carrera',
    'TAB_NATIONAL_TEAM': 'Selección Nacional',
    'NATIONAL_TEAM_HUB': 'Centro de la Selección',
    'PANEL_CARD_EVENT': 'EVENTO DE CARTAS',
    'PANEL_CAREER_SUMMARY': 'RESUMEN DE CARRERA',
    'PANEL_RETIREMENT': 'RETIRO',
    'ATTR_SAVING': 'Atajadas',
    'ATTR_REFLEXES': 'Reflejos',
    'ATTR_HANDLING': 'Agarre',
    'ATTR_POSITIONING': 'Ubicación',
    'ATTR_AERIAL_REACH': 'Alcance Aéreo',
    'ATTR_ONE_ON_ONE': 'Mano a Mano',
    'ATTR_DISTRIBUTION': 'Saque / Pase',
    'ATTR_PRO': 'Progresión',
    'ATTR_DEF': 'Defensa',
    'ATTR_CRE': 'Creación',
    'ATTR_MEN': 'Mentalidad',
    'ATTR_GOA': 'Gol',
    'ATTR_PHY': 'Físico',
    'SETTINGS_TEST_MODE': 'MODO DE PRUEBA',
    'SETTINGS_TEST_MODE_DESC': 'Mostrar opciones de desarrollo y pruebas durante el juego.',
    'OPTION_ON': 'ACTIVADO',
    'OPTION_OFF': 'DESACTIVADO',
    'SETTINGS_APP_PREFERENCES': 'Preferencias de la App y Tamaño de Fuente',
    'SETTINGS_FONT_SIZE': 'Escala de Tamaño de Fuente',
    'FONT_SIZE_SM': 'Chico',
    'FONT_SIZE_MD': 'Medio',
    'FONT_SIZE_LG': 'Grande',
    'BTN_RETURN_TO_SIMULATION': 'Volver a la Simulación',
  },
  'pt-BR': {
    'UC_COMMON': 'Comum',
    'UC_TIER': 'Nível',
    'UC_INIT_HEADER': 'INICIALIZAÇÃO DA CARTA',
    'UC_STEP_1_3': 'ETAPA 1 DE 3',
    'UC_TITLE': 'Inicialize sua Promessa',
    'UC_SUBTITLE': 'Personalize identidade e atributos ou escolha uma lenda predefinida',
    'CRASH_SHARE_SUCCESS': 'Relatório de erros copiado para a área de transferência!',
    'MM_NO_SAVE_DESC': 'Nenhum jogo salvo encontrado. Comece uma nova carreira.',
    'MM_ACHIEVEMENTS_DESC': 'Veja sua sala de troféus, conquistas e recordes de carreira.',
    'BTN_SELECT': 'Selecionar',
    'SHOW': 'MOSTRAR',
    'CASH': 'Saldo',
    'PARENTS_ADVICE': 'CONSELHO DOS PAIS',
    'HIDE': 'ESCONDER',
    'PANEL_CHEMISTRY': 'QUÍMICA',
    'PANEL_FITNESS': 'FORMA FÍSICA',
    'HEAL': 'CURAR',
    'AVAIL_MONEY': 'Dinheiro Disponível',
    'FAME': 'FAMA',
    'BAD_REP': 'MÁ REPUTAÇÃO',
    'TRAINING_PROGRESS': 'PROGRESSO DE TREINO',
    'CAREER_CALENDAR': 'CALENDÁRIO DE CARREIRA',
    'PLAYER_CARD_OVERVIEW': 'VISÃO GERAL DA CARTA',
    'CUSTOMIZATION': 'CUSTOMIZAÇÃO',
    'PANEL_CAREER_PANELS': 'PAINÉIS DE CARREIRA',
    'TAB_STORE': 'Loja e Equipamentos',
    'TAB_CARDS': 'Coleção de Cartas',
    'TAB_DEV': 'Evolução e Atributos',
    'TAB_ACCOUNTING': 'Finanças e Contabilidade',
    'TAB_MANAGER': 'Empresário e Treinador',
    'TAB_SETTINGS': 'Configurações',
    'TAB_TROPHIES': 'Sala de Troféus',
    'TAB_PERKS': 'Vantagens de Carreira',
    'TAB_NATIONAL_TEAM': 'Seleção Nacional',
    'NATIONAL_TEAM_HUB': 'Centro da Seleção',
    'PANEL_CARD_EVENT': 'EVENTO DE CARTAS',
    'PANEL_CAREER_SUMMARY': 'RESUMO DE CARREIRA',
    'PANEL_RETIREMENT': 'APOSENTADORIA',
    'ATTR_SAVING': 'Defesas',
    'ATTR_REFLEXES': 'Reflexos',
    'ATTR_HANDLING': 'Manuseio',
    'ATTR_POSITIONING': 'Posicionamento',
    'ATTR_AERIAL_REACH': 'Alcance Aéreo',
    'ATTR_ONE_ON_ONE': 'Um contra Um',
    'ATTR_DISTRIBUTION': 'Distribuição',
    'ATTR_PRO': 'Progressão',
    'ATTR_DEF': 'Defesa',
    'ATTR_CRE': 'Criação',
    'ATTR_MEN': 'Mentalidade',
    'ATTR_GOA': 'Finalização',
    'ATTR_PHY': 'Físico',
    'SETTINGS_TEST_MODE': 'MODO DE TESTE',
    'SETTINGS_TEST_MODE_DESC': 'Mostrar opções de desenvolvimento e testes durante o jogo.',
    'OPTION_ON': 'LIGADO',
    'OPTION_OFF': 'DESLIGADO',
    'SETTINGS_APP_PREFERENCES': 'Preferências do App e Tamanho da Fonte',
    'SETTINGS_FONT_SIZE': 'Escala de Tamanho da Fonte',
    'FONT_SIZE_SM': 'Pequeno',
    'FONT_SIZE_MD': 'Médio',
    'FONT_SIZE_LG': 'Grande',
    'BTN_RETURN_TO_SIMULATION': 'Voltar à Simulação',
  },
  'fr-FR': {
    'UC_COMMON': 'Commun',
    'UC_TIER': 'Niveau',
    'UC_INIT_HEADER': 'INITIALISATION DE LA CARTE',
    'UC_STEP_1_3': 'ÉTAPE 1 SUR 3',
    'UC_TITLE': 'Initialisez votre Prodige',
    'UC_SUBTITLE': 'Personnalisez l’identité et les attributs ou choisissez une légende prédéfinie',
    'CRASH_SHARE_SUCCESS': 'Rapport d’erreur copié dans le presse-papiers !',
    'MM_NO_SAVE_DESC': 'Aucune sauvegarde active trouvée. Commencez une nouvelle carrière.',
    'MM_ACHIEVEMENTS_DESC': 'Consultez votre armoire à trophées, vos exploits et vos records.',
    'BTN_SELECT': 'Sélectionner',
    'SHOW': 'AFFICHER',
    'CASH': 'Trésorerie',
    'PARENTS_ADVICE': 'CONSEIL DES PARENTS',
    'HIDE': 'MASQUER',
    'PANEL_CHEMISTRY': 'CHIMIE',
    'PANEL_FITNESS': 'FORME PHYSIQUE',
    'HEAL': 'SOIGNER',
    'AVAIL_MONEY': 'Fonds Disponibles',
    'FAME': 'NOTORIÉTÉ',
    'BAD_REP': 'MAUVAISE RÉPUTATION',
    'TRAINING_PROGRESS': 'PROGRESSION DE L’ENTRAÎNEMENT',
    'CAREER_CALENDAR': 'CALENDRIER DE CARRIÈRE',
    'PLAYER_CARD_OVERVIEW': 'APERÇU DE LA CARTE',
    'CUSTOMIZATION': 'PERSONNALISATION',
    'PANEL_CAREER_PANELS': 'PANNEAUX DE CARRIÈRE',
    'TAB_STORE': 'Boutique & Équipements',
    'TAB_CARDS': 'Collection de Cartes',
    'TAB_DEV': 'Développement & Attributs',
    'TAB_ACCOUNTING': 'Comptabilité & Finances',
    'TAB_MANAGER': 'Agent & Entraîneur',
    'TAB_SETTINGS': 'Paramètres',
    'TAB_TROPHIES': 'Armoire à Trophées',
    'TAB_PERKS': 'Atouts de Carrière',
    'TAB_NATIONAL_TEAM': 'Équipe Nationale',
    'NATIONAL_TEAM_HUB': 'Centre de la Sélection',
    'PANEL_CARD_EVENT': 'ÉVÉNEMENT DE CARTES',
    'PANEL_CAREER_SUMMARY': 'RÉSUMÉ DE CARRIÈRE',
    'PANEL_RETIREMENT': 'RETRAITE',
    'ATTR_SAVING': 'Arrêts',
    'ATTR_REFLEXES': 'Réflexes',
    'ATTR_HANDLING': 'Prise de balle',
    'ATTR_POSITIONING': 'Placement',
    'ATTR_AERIAL_REACH': 'Détente Aérienne',
    'ATTR_ONE_ON_ONE': 'Face à Face',
    'ATTR_DISTRIBUTION': 'Relance',
    'ATTR_PRO': 'Progression',
    'ATTR_DEF': 'Défense',
    'ATTR_CRE': 'Création',
    'ATTR_MEN': 'Mentalité',
    'ATTR_GOA': 'Finition',
    'ATTR_PHY': 'Physique',
    'SETTINGS_TEST_MODE': 'MODE TEST',
    'SETTINGS_TEST_MODE_DESC': 'Afficher les options de développement et de test en cours de jeu.',
    'OPTION_ON': 'ACTIVÉ',
    'OPTION_OFF': 'DÉSACTIVÉ',
    'SETTINGS_APP_PREFERENCES': 'Préférences de l’App et Taille de Police',
    'SETTINGS_FONT_SIZE': 'Échelle de la Police',
    'FONT_SIZE_SM': 'Petit',
    'FONT_SIZE_MD': 'Moyen',
    'FONT_SIZE_LG': 'Grand',
    'BTN_RETURN_TO_SIMULATION': 'Retour à la Simulation',
  }
};

const langs = ['en-GB', 'es-ES', 'es-AR', 'pt-BR', 'fr-FR'];

langs.forEach(lang => {
  const entries = keysToAdd[lang];
  const lines = Object.entries(entries).map(([k, v]) => "    '" + k + "': " + JSON.stringify(v) + ",").join('\n');
  
  let nextMarker;
  if (lang === 'en-GB') nextMarker = "  'es-ES': {";
  else if (lang === 'es-ES') nextMarker = "  'es-AR': {";
  else if (lang === 'es-AR') nextMarker = "  'pt-BR': {";
  else if (lang === 'pt-BR') nextMarker = "  'fr-FR': {";
  else if (lang === 'fr-FR') nextMarker = "const CARD_TRANSLATIONS";

  const nextPos = content.indexOf(nextMarker);
  if (nextPos === -1) {
    console.error('Marker not found for', lang, nextMarker);
    return;
  }

  const sub = content.substring(0, nextPos);
  const lastClosingBrace = sub.lastIndexOf('  },');
  if (lastClosingBrace === -1) {
    console.error('Closing brace not found for', lang);
    return;
  }

  content = content.substring(0, lastClosingBrace) + lines + '\n  },\n' + content.substring(nextPos);
});

fs.writeFileSync(file, content, 'utf8');
console.log('Successfully updated localizationSystem.ts!');
